spring:
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    port: 5672
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        input:
          customer:
            acknowledge-mode: manual
#            auto-bind-dlq: true
#            republish-to-dlq: true
          destination: rabbitmq
          group: hello
#          content-type: application/json
#        output:
#          group: hello

server:
  port: 8080
#          content-type: application/json