
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          skipSslValidation: true
          searchPaths: foo,bar*
  application:
    name: foo
  profiles:
    active: dev,mysql
server:
  port: 8888