spring:
  cloud:
    stream:
      bindings:
        output: #注意此处是output
          destination: rabbitmq
          group: hello
          binder: my_binder #单个channel设置binder
      binders:
        my_binder:
          type: rabbit #中间件类型为rabbitmq
          environment:
            spring:
              rabbitmq:
                host: localhost
                username: admin
                password: admin
                port: 5672
                virtual-host: /
      default-binder: my_binder #全局设置默认binder
server:
  port: 8081