spring:
  cloud:
    stream:
      bindings:
        input:
          destination: rabbitmq
          group: hello
          binder: my_rabbit
      rabbit:
        bindings:
          input:
            consumer:
              acknowledge-mode: manual
              auto-bind-dlq: true
              republish-to-dlq: true
              deadLetterQueueName: errorChannel
              deadLetterExchange: dlq
      default-binder: my_rabbit
      binders:
        my_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                username: admin
                password: admin
                port: 5672
                virtual-host: /

server:
  port: 8080