server:
  port: 9080
spring:
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        input:
          binder: activemq #当项目中存在多个消息中间件：activemq、kafka，必须指定要绑定哪一个中间件
          destination: aq-destination
          group: aqgroup
      binders:
        activemq:
          type: activemq
          environment:
            spring:
              cloud:
                stream:
                  activemq:
                    binder:
                      brokerUrl: tcp://localhost:61616
                      user: admin
                      password: admin

  appliction:
    name: sc-activemq
  jms:
    pub-sub-domain: true #默认情况下activemq提供的是queue模式，若要使用topic模式需要配置pub-sub-domain为true